#!/bin/bash

set -o errexit

readonly OUTPUT="output"



echo "Hello! pid=$BASHPID"
echo "1 pid of myprocess=$!" $!


./keiko


echo "2 pid of myprocess=$!"









# ./philo 4 410 200 200

#  reredirect -o OUTPUT $!

#echo "jajajaja" > output

#./philo 4 410 200 200 > output
#timeout 1 ./philo 4 410 200 200 > output

# sleep 3

# RET=$(grep -c "ja" output)

# if [ $RET != 0 ]
# then
# 	echo "yes $RET"
# fi

# echo $RET




# say_hello() {
#   echo "Hello! pid=$BASHPID"
# }

# Calls `say hello` from the main
# process.
#
# Logs the hello message to the process
# stdout as no redirection has been
# performed at this point.


# Creates a subshell (in a sub process)
# and then calls `say_hello`.
#
# The subshell that gets created has both
# stdout and stderr redirected to the LOG
# file `/var/log/script.log`.
# (
#   say_hello
#   sleep 3600
# ) &> $LOG_FILE